### ISSUE TITLE
Enable automatic diagram preview

### ISSUE THREAD

**Issue by LuboTerifaj** [serverlessworkflow/vscode-extension#29]
**What would you like to be added**:

Enable automatic diagram preview.

The diagram should automatically open when you open the workflow file.

**Why is this needed**: 

If you open any serverless workflow file (*.sw.json, *.sw.yml), you have to open the Command Palette (⇧⌘P or Ctrl + Shift + P), then type and select the option "Serverless Workflow: Preview Diagram" to see the workflow's diagram.

**Comment by JBBianchi** [comment]
Or just right-click on the file in the explorer or inside the editor.

**Comment by JBBianchi** [comment]
@LuboTerifaj would you be so kind to test #30 please ?
